color0 #0b2454
color1 #c93d45
color2 #c93d45
color3 #f5453f
color4 #c93d45
color5 #c93d45
color6 #c93d45
color7 #eaf0fb
color8 #4e71a8
color9 #f5453f
color10 #ff6b6b
color11 #ff6b3d
color12 #ff6b6b
color13 #ff6b6b
color14 #ff6b6b
color15 #ffffff

cursor                #f5453f
cursor_text_color     #000000
background            #000000
foreground            #eaf0fb
selection_foreground  #0a1e42
selection_background  #3d7eff
active_border_color   #f5453f
inactive_border_color #000d2c
url_color             #f5453f

active_tab_foreground   #0a1e42
active_tab_background   #f5453f
inactive_tab_foreground #9bb4dc
inactive_tab_background #000d2c
cursor_trail_color      #9bb4dc
